/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.bnsplits.view;

import javax.swing.JScrollPane;

/**
 *
 * @author bnsplit
 */
public class TestFrame extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestFrame.class.getName());

  /**
   * Creates new form TestFrame
   */
  public TestFrame() {
    initComponents();
    setupTableData();
  }

  private void setupTableData() {
    // Créer un modèle de table avec des données de test
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new Object[][] {
            { "John Doe", "john.doe@email.com", "Developer", "Active" },
            { "Jane Smith", "jane.smith@email.com", "Designer", "Active" },
            { "Mike Johnson", "mike.j@email.com", "Manager", "Inactive" },
            { "Sarah Williams", "sarah.w@email.com", "Tester", "Active" },
            { "Tom Brown", "tom.brown@email.com", "Developer", "Active" },
            { "Emily Davis", "emily.d@email.com", "Analyst", "Pending" },
            { "David Wilson", "david.w@email.com", "Developer", "Active" },
            { "Lisa Anderson", "lisa.a@email.com", "Designer", "Active" }
        },
        new String[] {
            "Name", "Email", "Role", "Status"
        }) {
      @Override
      public boolean isCellEditable(int row, int column) {
        return false; // Rendre toutes les cellules non éditables
      }
    };

    // Désactiver les scrollbars
    // jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
    // jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

    customTable1.setModel(model);

    // Optionnel : ajuster la largeur des colonnes
    customTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
    customTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
    customTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
    customTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    customTextField2 = new org.bnsplits.view.components.CustomTextField();
    customPasswordField2 = new org.bnsplits.view.components.CustomPasswordField();
    customButton1 = new org.bnsplits.view.components.CustomButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    customTable1 = new org.bnsplits.view.components.CustomTable();
    customCard1 = new org.bnsplits.view.components.CustomCard();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    customTextField2.setText("customTextField2");

    customPasswordField2.setText("customPasswordField2");
    customPasswordField2.addActionListener(this::customPasswordField2ActionPerformed);

    customButton1.setText("customButton1");

    customTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {
            { null, null, null, null },
            { null, null, null, null },
            { null, null, null, null },
            { null, null, null, null }
        },
        new String[] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }));
    jScrollPane1.setViewportView(customTable1);

    javax.swing.GroupLayout customCard1Layout = new javax.swing.GroupLayout(customCard1);
    customCard1.setLayout(customCard1Layout);
    customCard1Layout.setHorizontalGroup(
        customCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE));
    customCard1Layout.setVerticalGroup(
        customCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customCard1, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customTextField2, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customCard1, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(customTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void customPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_customPasswordField2ActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_customPasswordField2ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new TestFrame().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private org.bnsplits.view.components.CustomButton customButton1;
  private org.bnsplits.view.components.CustomCard customCard1;
  private org.bnsplits.view.components.CustomPasswordField customPasswordField2;
  private org.bnsplits.view.components.CustomTable customTable1;
  private org.bnsplits.view.components.CustomTextField customTextField2;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
